### ISSUE TITLE
Spotify Listener doesn't include special charcters

### ISSUE THREAD

**Issue by auadams** [Devoxin/JukeBot#16]
It apears the format of spotify links was never updated to relfect the fact that symbols may be in a link. IE

https://open.spotify.com/track/7ETQN0uPcdGk4D43LtZI45?si=d302e460b7d046cc

https://open.spotify.com/track/479piqfYJyfsuQ74HY9TMB?si=2b0947516bbd4f9b

to solve this we just need to update the regex in SpotifyTrackLoader.kt to the following

`
private val TRACK_PATTERN = "^(?:https?://(?:open\\.)?spotify\\.com|spotify)([/:])track/([a-zA-Z0-9?=]+)".toPattern()
`

**Comment by devoxin** [comment]
Fixed in [#9d3f0de](https://github.com/Devoxin/JukeBot/commit/9d3f0de846ee4c4a94736c986d62580d4f48a220)
